---
sudo: required
language: ruby
cache: bundler

# necessary for docker to work
dist: trusty
services:
  - docker

bundler_args: --without integration tools

before_install:
  - gem install bundler
  - gem --version

matrix:
  include:
  - rvm: 1.9.3
  - rvm: 2.0
  - rvm: 2.2
    script: bundle exec rake test test:docker config=test-travis-1.yaml
  - rvm: 2.2
    script: bundle exec rake test:docker config=test-travis-2.yaml
